{{- define "common.service" -}}
{{- $fullName := include "common.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- with .Values.service.ports }}
  {{- range $k, $v := . }}
    - name: {{ $v.name }}
      port: {{ $v.port }}
      targetPort: {{ $v.targetPort | default $v.port }}
      protocol: {{ $v.protocol | default "TCP" }}
      {{- if $v.nodePort }}
      nodePort: {{ $v.nodePort }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end -}}
