replicaCount: 1

image:
  repository: jonpulsifer/nested
  pullPolicy: IfNotPresent
  tag: latest

ports:
  - name: http-alt
    containerPort: 3000
    protocol: TCP

# env:
# - name: NODE_IP
#   valueFrom:
#     fieldRef:
#       fieldPath: status.hostIP
# - name: NODE_NAME
#   valueFrom:
#     fieldRef:
#       fieldPath: spec.nodeName
# - name: POD_IP
#   valueFrom:
#     fieldRef:
#       fieldPath: status.podIP
# - name: POD_NAME
#   valueFrom:
#     fieldRef:
#       fieldPath: metadata.name

service:
  type: ClusterIP
  ports:
    - name: http-alt
      port: 8080
      targetPort: 3000

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    hajimari.io/enable: "true"
    hajimari.io/icon: sync
  hosts:
    - host: &host "application.example.com"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: *host
      hosts:
        - *host

probes:
  enabled: false
  liveness:
    enabled: true
    httpGet:
      path: /health
      port: http-alt
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    enabled: true
    httpGet:
      path: /health
      port: http-alt
    initialDelaySeconds: 0
    periodSeconds: 10

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
  # fsGroup: 2000

containerSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
