# Default values for satisfactory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wolveix/satisfactory-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false

service:
  type: LoadBalancer
  ports:
    beacon:
      name: beacon
      port: &beaconport 15000
      targetPort: *beaconport
      protocol: UDP
    game:
      name: game
      port: &gameport 7777
      targetPort: *gameport
      protocol: UDP
    query:
      name: query
      port: &queryport 15777
      targetPort: *queryport
      protocol: UDP

env:
  AUTOPAUSE: false # -- pause game when no player is connected
  AUTOSAVEINTERVAL: 300 # -- autosave interval in seconds
  AUTOSAVENUM: 3 # -- number of rotating autosave files
  AUTOSAVEONDISCONNECT: true # -- autosave when last player disconnects
  CRASHREPORT: true # -- automatic crash reporting
  DEBUG: false # -- for debugging the server
  DISABLESEASONALEVENTS: false # -- disable the FICSMAS event (you miserable bastard)
  MAXPLAYERS: 3 # -- set the player limit for your server
  MAXOBJECTS: 2162688 # set the object limit for your server
  MAXTICKRATE: 30 # -- set the maximum sim tick rate for your server
  PGID: 1000 # -- set the group ID of the user the server will run as
  PUID: 1000 # -- set the user ID of the user the server will run as
  NETWORKQUALITY: 3 # -- set the network quality (1-3)
  ROOTLESS: true # -- run the container as a non-root user (requires PGID and PUID to be set)
  SERVERBEACONPORT: *beaconport # -- set the game's beacon port
  SERVERGAMEPORT: *gameport # -- set the game's port
  SERVERIP: 0.0.0.0 # -- set the game's ip (usually not needed)
  SERVERQUERYPORT: *queryport # -- set the game's query port
  SERVERSTREAMING: true # -- toggle whether the game utilizes asset streaming
  SKIPUPDATE: false # -- avoid updating the game on container start/restart
  STEAMBETA: false # -- set experimental game version
  TIMEOUT: 30 # -- set client timeout (in seconds)

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
