apiVersion: v2
name: echo-server
description: A Helm chart for Kubernetes
type: application
version: 0.1.5
appVersion: "0.3.4"
dependencies:
  - name: common
    version: 0.0.1
    repository: https://jonpulsifer.github.io/charts
